export const environment = {
  production: true,
  serverBasePath: 'https://bloomie-mock-api.azurewebsites.net/api/v1',
  usersEndpointPath: '/users',
  sessionsEndpointPath: '/sessions',
  skinProfilesEndpointPath: '/skin_profiles',
  facialScansEndpointPath: '/facial_scans',
  routinesEndpointPath: '/routines',
  routineItemsEndpointPath: '/routine_items',
  dailyTrackingsEndpointPath: '/daily_trackings',
  productsEndpointPath: '/products',
  productCompatibilitiesEndpointPath: '/product_compatibilities',
  favoriteProductsEndpointPath: '/favorite_products',
  dermatologistProfilesEndpointPath: '/dermatologist_profiles',
  dermatologistAvailabilitiesEndpointPath: '/dermatologist_availabilities',
  appointmentsEndpointPath: '/appointments',
  consultationsEndpointPath: '/consultations',
  paymentsEndpointPath: '/payments',
  plansEndpointPath: '/plans',
  subscriptionsEndpointPath: '/subscriptions',
  supportQueriesEndpointPath: '/support_queries',
  chatMessagesEndpointPath: '/chat_messages',
  authenticationLoginEndpointPath: '/authentication/sign-in',
  authenticationRegisterYoungAdultEndpointPath: '/authentication/sign-up/young-adult',
  authenticationRegisterDermatologistEndpointPath: '/authentication/sign-up/dermatologist',
  useMockAuthentication: true,
};
